apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: argocd
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"