spring.application.name=portfolio-backend

server.port=${PORT:8080}

##spring.datasource.url=jdbc:postgresql://localhost:5432/Portfolio
#spring.datasource.url=postgresql://portfolio_db_kg5o_user:Qa1UJ8JosS7GsbtS3mnacw2zfL37kom0@dpg-d6i3tdfgi27c7387sh9g-a/portfolio_db_kg5o
##spring.datasource.username=postgres
##spring.datasource.password=helloworld!
#spring.datasource.username=portfolio_db_kg5o_user
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://db:5432/Portfolio
spring.datasource.username=postgres
spring.datasource.password=helloworld!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

aws.region=ap-south-1
aws.bucket-name=neerajmittal-portfolio-assets

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB