apiVersion: v1
kind: Service
metadata:
  name: backend-service-green
  namespace: portfolio
spec:
  selector:
    app: backend-green
  type: ClusterIP
  ports:
    - port: 8080          
      targetPort: 8080    
