apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-green
  namespace: portfolio
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend-green
  template:
    metadata:
      labels:
        app: backend-green
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-headless:5432/Portfolio"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "helloworld!"
