apiVersion: v1
kind: Service
metadata:
  name: frontend-service-green
  namespace: portfolio
spec:
  selector:
    app: frontend-green
  type: ClusterIP
  ports:
    - port: 80             
      targetPort: 80       
