apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-green
  namespace: portfolio
  labels:
    app: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend-green
  template:
    metadata:
      labels:
        app: frontend-green
    spec:
      containers:
        - name: frontend
          image: neerajdeveloper/portfolio-frontend-vscode
          ports:
            - containerPort: 80              
