name: Ci BUild

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ---------------------------
      # Build Backend (Spring Boot)
      # ---------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Backend
        working-directory: portfolio/portfolio
        run: mvn clean package -DskipTests

      # ---------------------------
      # Build Frontend (React)
      # ---------------------------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        working-directory: frontend/portfolio
        run: npm install

      - name: Build Frontend
        working-directory: frontend/portfolio
        run: npm run build

      # ---------------------------
      # Docker Login
      # ---------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------------------------
      # Build & Push Backend Image
      # ---------------------------
      - name: Build Backend Docker Image
        working-directory: portfolio/portfolio
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend:latest .

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend:latest

      # ---------------------------
      # Build & Push Frontend Image
      # ---------------------------
      - name: Build Frontend Docker Image
        working-directory: frontend/portfolio
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest .

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest